apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: mike/auth
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY

# kubectl create secret generic jwt-secret --from-literal=JWT_KEY=asd
# kubectl config set-context --current --namespace=my-namespace
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
  namespace: ingress-nginx
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000